version: '3.8'

services:
    php-apache:
        container_name: php-apache
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - db
        links:
            - "db:db"
        volumes:
            - ./src:/var/www/html/
        ports:
            - 8000:80
        environment:
            MYSQL_HOSTNAME: db
            MYSQL_DATABASE: movie_rental_system
            MYSQL_USER: mrs
            MYSQL_PASSWORD: mrs

    db:
        container_name: db
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: movie_rental_system
            MYSQL_USER: mrs
            MYSQL_PASSWORD: mrs
        ports:
            - "9906:3306"
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - '8080:80'
        restart: always
        environment:
            PMA_HOST: db
        depends_on:
            - db